---
title: "Deliverable2Draft"
author: "A+T"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
council=read_xlsx("CouncilAge.xlsx")
```


```{r}
library(ggplot2)
base= ggplot(data = council,
             aes(x = Councilmember,
                 y = Age))
plot1 = base +  geom_segment(aes(x = Councilmember, xend = Councilmember, y = Age, yend = 35),  color="darkgrey")+
  geom_point(size=3, color="blue") +
               ylim(30,70)
plot1
```

```{r}
titleText='Ages of Seattle City Councilmembers'
subtext='How old are our elected officials?'
sourceText='Source: Wikipedia'
plot2 = plot1 + labs(title=titleText, subtitle = subtext,
                     caption = sourceText)
plot2
```

```{r}
plot3 = plot2 + theme_classic()
plot3
```

```{r}
plot4 = plot3 + coord_flip()

plot4
```

```{r}
plot5 = plot4 + geom_hline(yintercept = 35, 
                           linetype="dashed", 
                           size=1, 
                           alpha=0.3)
plot5
```
```{r}
plot6 = plot5 +  annotate(
  "text", label = "Median Age \n in Seattle",
  x = 8.5, y = 32.3, size = 2.2, color = "black"
)
plot6

```

```{r}
plot7 = plot6 + theme(plot.title = element_text(hjust = 0.5),
                      plot.subtitle = element_text(hjust = 0.5),
                      axis.title.y = element_blank())
plot7
```

